"""Generate _regions_generated.py from the catalog: `uv run python -m space_mango._codegen`."""

from __future__ import annotations

from pathlib import Path

from space_mango.models import REGIONS, Region, filters_for

_HEADER = '''"""GENERATED by space_mango._codegen from models.py. Do not edit by hand."""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from space_mango.regions import RegionAPI
from space_mango.timeparse import TimeLike

if TYPE_CHECKING:
    from space_mango.result import MangoResult
'''


def _class_name(region: Region) -> str:
    return "".join(part.capitalize() for part in region.value.split("_")) + "API"


def _filter_doc(region: Region) -> list[str]:
    lines: list[str] = []
    for name, f in filters_for(region).items():
        unit = f" [{f.unit}]" if f.unit else ""
        lines.append(f"        {name}_min / {name}_max : {f.description}{unit}")
    return lines


def _filter_params(region: Region) -> list[str]:
    out: list[str] = []
    for name in filters_for(region):
        out.append(f"        {name}_min: float | None = None,")
        out.append(f"        {name}_max: float | None = None,")
    return out


def _render_class(region: Region) -> str:
    definition = REGIONS[region].definition.replace("\\", "\\\\").replace('"', "'")
    doc = "\n".join(_filter_doc(region))
    params = "\n".join(_filter_params(region))
    cls = _class_name(region)
    return f'''

class {cls}(RegionAPI):
    """{region.value}: {definition}"""

    name: ClassVar[str] = "{region.value}"
    definition: ClassVar[str] = "{definition}"

    def get_data(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        limit: int | None = None,
        cache: bool | None = None,
{params}
    ) -> MangoResult:
        """Download {region.value} data. start is inclusive, stop exclusive.

        Range filters (inclusive bounds):
{doc}
        """
        return self._call("get_data", locals())

    def count(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
{params}
    ) -> dict[str, float]:
        """n_rows, est_mb and download_mb_estimate of get_data with the same arguments."""
        return self._call("count", locals())
'''


def render_regions_module() -> str:
    body = "".join(_render_class(r) for r in Region)
    mapping = "\n".join(f'    "{r.value}": {_class_name(r)},' for r in Region)
    return f"{_HEADER}{body}\n\nREGION_APIS: dict[str, type[RegionAPI]] = {{\n{mapping}\n}}\n"


if __name__ == "__main__":
    target = Path(__file__).with_name("_regions_generated.py")
    target.write_text(render_regions_module())
    print(f"wrote {target}")
