"""GENERATED by space_mango._codegen from models.py. Do not edit by hand."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, ClassVar

from space_mango.regions import RegionAPI
from space_mango.timeparse import TimeLike

if TYPE_CHECKING:
    from space_mango.result import MangoResult


class MagnetosphereAPI(RegionAPI):
    """magnetosphere: Inside the magnetopause: closed-field-line magnetosphere sampled by the spacecraft (machine-learning region classification, Nguyen et al. 2022)."""

    name: ClassVar[str] = "magnetosphere"
    definition: ClassVar[str] = "Inside the magnetopause: closed-field-line magnetosphere sampled by the spacecraft (machine-learning region classification, Nguyen et al. 2022)."

    def get_data(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        limit: int | None = None,
        cache: bool | None = None,
        frame: str | None = None,
        cone: Sequence[float] | None = None,
        clock: float | Sequence[float] | None = None,
        tilt: Sequence[float] | None = None,
        bz_imf_min: float | None = None,
        bz_imf_max: float | None = None,
        by_imf_min: float | None = None,
        by_imf_max: float | None = None,
        bx_imf_min: float | None = None,
        bx_imf_max: float | None = None,
        pd_sw_min: float | None = None,
        pd_sw_max: float | None = None,
        np_sw_min: float | None = None,
        np_sw_max: float | None = None,
        tp_sw_min: float | None = None,
        tp_sw_max: float | None = None,
        vx_sw_min: float | None = None,
        vx_sw_max: float | None = None,
        beta_sw_min: float | None = None,
        beta_sw_max: float | None = None,
        ma_sw_min: float | None = None,
        ma_sw_max: float | None = None,
        tilt_min: float | None = None,
        tilt_max: float | None = None,
        x_gsm_min: float | None = None,
        x_gsm_max: float | None = None,
        y_gsm_min: float | None = None,
        y_gsm_max: float | None = None,
        z_gsm_min: float | None = None,
        z_gsm_max: float | None = None,
        d_msp_min: float | None = None,
        d_msp_max: float | None = None,
        np_min: float | None = None,
        np_max: float | None = None,
        tp_min: float | None = None,
        tp_max: float | None = None,
        bz_min: float | None = None,
        bz_max: float | None = None,
    ) -> MangoResult:
        """Download magnetosphere data. start is inclusive, stop exclusive.

        Range filters (inclusive bounds):
        bz_imf_min / bz_imf_max : IMF Bz — southward (<0) drives reconnection [nT]
        by_imf_min / by_imf_max : IMF By — controls reconnection geometry and asymmetry [nT]
        bx_imf_min / bx_imf_max : IMF Bx — cone angle / Parker spiral orientation [nT]
        pd_sw_min / pd_sw_max : Solar wind dynamic pressure [nPa]
        np_sw_min / np_sw_max : Solar wind proton density [cm⁻³]
        tp_sw_min / tp_sw_max : Solar wind proton temperature [K]
        vx_sw_min / vx_sw_max : Solar wind velocity X (GSM); negative (anti-sunward), so faster wind is more negative [km/s]
        beta_sw_min / beta_sw_max : Solar wind plasma beta
        ma_sw_min / ma_sw_max : Solar wind Alfvén Mach number
        tilt_min / tilt_max : Dipole tilt angle (positive near June solstice) [rad]
        x_gsm_min / x_gsm_max : X GSM coordinate [R_E]
        y_gsm_min / y_gsm_max : Y GSM coordinate [R_E]
        z_gsm_min / z_gsm_max : Z GSM coordinate [R_E]
        d_msp_min / d_msp_max : Relative distance Earth(0)–magnetopause(1): |r| / R_mp
        np_min / np_max : Local plasma density [cm⁻³]
        tp_min / tp_max : Local plasma temperature [K]
        bz_min / bz_max : Local Bz (GSM) [nT]
        frame='gsm' | 'pgsm'; cone/clock=[min, max] select on GSM values;
        tilt=[min, max] in degrees (with the tilt symmetry in pgsm).
        """
        return self._call("get_data", locals())

    def count(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        frame: str | None = None,
        cone: Sequence[float] | None = None,
        clock: float | Sequence[float] | None = None,
        tilt: Sequence[float] | None = None,
        bz_imf_min: float | None = None,
        bz_imf_max: float | None = None,
        by_imf_min: float | None = None,
        by_imf_max: float | None = None,
        bx_imf_min: float | None = None,
        bx_imf_max: float | None = None,
        pd_sw_min: float | None = None,
        pd_sw_max: float | None = None,
        np_sw_min: float | None = None,
        np_sw_max: float | None = None,
        tp_sw_min: float | None = None,
        tp_sw_max: float | None = None,
        vx_sw_min: float | None = None,
        vx_sw_max: float | None = None,
        beta_sw_min: float | None = None,
        beta_sw_max: float | None = None,
        ma_sw_min: float | None = None,
        ma_sw_max: float | None = None,
        tilt_min: float | None = None,
        tilt_max: float | None = None,
        x_gsm_min: float | None = None,
        x_gsm_max: float | None = None,
        y_gsm_min: float | None = None,
        y_gsm_max: float | None = None,
        z_gsm_min: float | None = None,
        z_gsm_max: float | None = None,
        d_msp_min: float | None = None,
        d_msp_max: float | None = None,
        np_min: float | None = None,
        np_max: float | None = None,
        tp_min: float | None = None,
        tp_max: float | None = None,
        bz_min: float | None = None,
        bz_max: float | None = None,
    ) -> dict[str, float]:
        """n_rows, est_mb and download_mb_estimate of get_data with the same arguments."""
        return self._call("count", locals())


class MagnetosheathAPI(RegionAPI):
    """magnetosheath: Between the bow shock and the magnetopause: shocked solar wind (machine-learning region classification, Nguyen et al. 2022)."""

    name: ClassVar[str] = "magnetosheath"
    definition: ClassVar[str] = "Between the bow shock and the magnetopause: shocked solar wind (machine-learning region classification, Nguyen et al. 2022)."

    def get_data(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        limit: int | None = None,
        cache: bool | None = None,
        frame: str | None = None,
        cone: Sequence[float] | None = None,
        clock: float | Sequence[float] | None = None,
        bz_imf_min: float | None = None,
        bz_imf_max: float | None = None,
        by_imf_min: float | None = None,
        by_imf_max: float | None = None,
        bx_imf_min: float | None = None,
        bx_imf_max: float | None = None,
        pd_sw_min: float | None = None,
        pd_sw_max: float | None = None,
        np_sw_min: float | None = None,
        np_sw_max: float | None = None,
        tp_sw_min: float | None = None,
        tp_sw_max: float | None = None,
        vx_sw_min: float | None = None,
        vx_sw_max: float | None = None,
        beta_sw_min: float | None = None,
        beta_sw_max: float | None = None,
        ma_sw_min: float | None = None,
        ma_sw_max: float | None = None,
        x_gsm_min: float | None = None,
        x_gsm_max: float | None = None,
        y_gsm_min: float | None = None,
        y_gsm_max: float | None = None,
        z_gsm_min: float | None = None,
        z_gsm_max: float | None = None,
        d_msh_min: float | None = None,
        d_msh_max: float | None = None,
        np_min: float | None = None,
        np_max: float | None = None,
        tp_min: float | None = None,
        tp_max: float | None = None,
        bz_min: float | None = None,
        bz_max: float | None = None,
    ) -> MangoResult:
        """Download magnetosheath data. start is inclusive, stop exclusive.

        Range filters (inclusive bounds):
        bz_imf_min / bz_imf_max : IMF Bz — southward (<0) drives reconnection [nT]
        by_imf_min / by_imf_max : IMF By — controls reconnection geometry and asymmetry [nT]
        bx_imf_min / bx_imf_max : IMF Bx — cone angle / Parker spiral orientation [nT]
        pd_sw_min / pd_sw_max : Solar wind dynamic pressure [nPa]
        np_sw_min / np_sw_max : Solar wind proton density [cm⁻³]
        tp_sw_min / tp_sw_max : Solar wind proton temperature [K]
        vx_sw_min / vx_sw_max : Solar wind velocity X (GSM); negative (anti-sunward), so faster wind is more negative [km/s]
        beta_sw_min / beta_sw_max : Solar wind plasma beta
        ma_sw_min / ma_sw_max : Solar wind Alfvén Mach number
        x_gsm_min / x_gsm_max : X GSM coordinate [R_E]
        y_gsm_min / y_gsm_max : Y GSM coordinate [R_E]
        z_gsm_min / z_gsm_max : Z GSM coordinate [R_E]
        d_msh_min / d_msh_max : Relative distance magnetopause(0)–bow shock(1): (|r| - R_mp) / (R_bs - R_mp)
        np_min / np_max : Local plasma density [cm⁻³]
        tp_min / tp_max : Local plasma temperature [K]
        bz_min / bz_max : Local Bz (GSM) [nT]
        frame='gsm' | 'swi' | 'pgsm'; cone=[min, max] and clock=[min, max] select on GSM
        values, or (swi/pgsm) the cone from -V_sw; in pgsm clock is one target value.
        """
        return self._call("get_data", locals())

    def count(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        frame: str | None = None,
        cone: Sequence[float] | None = None,
        clock: float | Sequence[float] | None = None,
        bz_imf_min: float | None = None,
        bz_imf_max: float | None = None,
        by_imf_min: float | None = None,
        by_imf_max: float | None = None,
        bx_imf_min: float | None = None,
        bx_imf_max: float | None = None,
        pd_sw_min: float | None = None,
        pd_sw_max: float | None = None,
        np_sw_min: float | None = None,
        np_sw_max: float | None = None,
        tp_sw_min: float | None = None,
        tp_sw_max: float | None = None,
        vx_sw_min: float | None = None,
        vx_sw_max: float | None = None,
        beta_sw_min: float | None = None,
        beta_sw_max: float | None = None,
        ma_sw_min: float | None = None,
        ma_sw_max: float | None = None,
        x_gsm_min: float | None = None,
        x_gsm_max: float | None = None,
        y_gsm_min: float | None = None,
        y_gsm_max: float | None = None,
        z_gsm_min: float | None = None,
        z_gsm_max: float | None = None,
        d_msh_min: float | None = None,
        d_msh_max: float | None = None,
        np_min: float | None = None,
        np_max: float | None = None,
        tp_min: float | None = None,
        tp_max: float | None = None,
        bz_min: float | None = None,
        bz_max: float | None = None,
    ) -> dict[str, float]:
        """n_rows, est_mb and download_mb_estimate of get_data with the same arguments."""
        return self._call("count", locals())


class SolarWindAPI(RegionAPI):
    """solar_wind: Upstream of the bow shock: pristine solar wind measured in situ by the same spacecraft (machine-learning region classification, Nguyen et al. 2022)."""

    name: ClassVar[str] = "solar_wind"
    definition: ClassVar[str] = "Upstream of the bow shock: pristine solar wind measured in situ by the same spacecraft (machine-learning region classification, Nguyen et al. 2022)."

    def get_data(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        limit: int | None = None,
        cache: bool | None = None,
        frame: str | None = None,
        x_gsm_min: float | None = None,
        x_gsm_max: float | None = None,
        y_gsm_min: float | None = None,
        y_gsm_max: float | None = None,
        z_gsm_min: float | None = None,
        z_gsm_max: float | None = None,
        np_min: float | None = None,
        np_max: float | None = None,
        tp_min: float | None = None,
        tp_max: float | None = None,
        bz_min: float | None = None,
        bz_max: float | None = None,
    ) -> MangoResult:
        """Download solar_wind data. start is inclusive, stop exclusive.

        Range filters (inclusive bounds):
        x_gsm_min / x_gsm_max : X GSM coordinate [R_E]
        y_gsm_min / y_gsm_max : Y GSM coordinate [R_E]
        z_gsm_min / z_gsm_max : Z GSM coordinate [R_E]
        np_min / np_max : Local plasma density [cm⁻³]
        tp_min / tp_max : Local plasma temperature [K]
        bz_min / bz_max : Local Bz (GSM) [nT]
        frame='gsm' returns the GSM columns and scalars.
        """
        return self._call("get_data", locals())

    def count(
        self,
        *,
        columns: str | list[str] | None = None,
        spacecraft: str | list[str] | None = None,
        start: TimeLike = None,
        stop: TimeLike = None,
        sw_paired_only: bool = False,
        normalized_only: bool = False,
        frame: str | None = None,
        x_gsm_min: float | None = None,
        x_gsm_max: float | None = None,
        y_gsm_min: float | None = None,
        y_gsm_max: float | None = None,
        z_gsm_min: float | None = None,
        z_gsm_max: float | None = None,
        np_min: float | None = None,
        np_max: float | None = None,
        tp_min: float | None = None,
        tp_max: float | None = None,
        bz_min: float | None = None,
        bz_max: float | None = None,
    ) -> dict[str, float]:
        """n_rows, est_mb and download_mb_estimate of get_data with the same arguments."""
        return self._call("count", locals())


REGION_APIS: dict[str, type[RegionAPI]] = {
    "magnetosphere": MagnetosphereAPI,
    "magnetosheath": MagnetosheathAPI,
    "solar_wind": SolarWindAPI,
}
